### ISSUE TITLE
SRG Request a age-1 index (survey year) analyses

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#846]
# 2022 Assessment

SRG request # 8

>The SRG encourages the JTC to include a complete reproduction of the executive summary incorporating the age-1 index in the next assessment and, if time permits, the retrospective analyses.

- [x] SS run with age-1 index
- [x] executive summary text
- [x] retrospective analysis
- [x] squid plot

**Comment by aaronmberger-nwfsc** [comment]
I think we should have a discussion about whether the age-1 index remains a sensitivity or part of the base model.  If used in the base model, then the sensitivity would be without.  I'll add this to our internal meeting agenda.

**Comment by kellijohnson-NOAA** [comment]
@cgrandin - thought that the reason it was not originally in the model was because they do not survey shallower than 50 m. But, some years they have gone shallower than 50 m and not found a large amount of young Pacific Hake.
@andrew-edwards - curious why the survey team changed their mind on putting it as the base? @kellijohnson-NOAA responded with as long as it is caveated with the knowledge that the survey was not designed to target these young ages. Andy looked at the last assessment, which had more uncertainty in the appendix than the base model.
@aaronmberger-nwfsc - commented that it would be good in the future to look at the coastal pelagic species acoustic survey to see if an acoustic signature for Pacific Hake can be found, but this would be future research. Not using it is a decision too. We **ARE** using a long-term average assumption. The index has pointed us in the right direction every year? Is this true in reality? 

## Tasks
- [ ] quantify the number of years that the survey has correctly informed the model about future recruitment given the data that were accumulated in the subsequent year (AMB)

**Comment by aaronmberger-nwfsc** [comment]
I'm checking the box here because it is partially done.  There's two approaches: 1) look within a model and we do that with our retrospective squid plots.  This does show that it gets us nearer to the eventual settle point one year earlier (not perfect but an improvement).  2) Among model evaluation - I only went back to as far back as the 2018 cohort and it got the direction right and in absolute sense subsequent years of (acoustic survey and fishery) data confirmed that the age-1 survey was advantageous assumption and much better than average recruitment at the time.  In order to go further back, we'd have to go back to the 2016 assessment, then 2014, 2012 and so on.

**Comment by andrew-edwards** [comment]
Don't fully understand point 2) above, but we have the squid plots and discussions, so think should be closed.
