### ISSUE TITLE
complete adding age-1 index to "base" model for 2022

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#869]
## Tasks

- [x] Include age-1 index and a 0.5 CV up to 2019 with estimated extra SD
- [x] Include 2021 estimate of age-1 index and a 0.5 CV with estimated extra SD
- [x] decrease input CV incrementally but still have extra SD estimated to see if the sum stabilizes to 0.75
- [x] Tail compression should be turned on to ensure that the estimated abundance of age-1 fish in the age-2+ survey remains estimated at zero rather than
- [x] fix extra SD for age-1 survey at 1.2 to see if down-weighting this survey leads to different fits
- [x] Add age-comp data as a trawl survey with no CPUE are specified and if it changes the answer to anything (KFJ)

## Notes

1. Age-1 fish that are sampled in the acoustic survey are not included in the age-proportion data for the age-2+ hake survey and never have been.
2. As expected, adding the age-1 survey does not decrease the calculated variability of recruitment deviations.

**Comment by kellijohnson-NOAA** [comment]
Thanks @aaronmberger-nwfsc for all of your hard work getting the runs completed within the time frame that we wanted to meet.

**Comment by andrew-edwards** [comment]
Why "_As expected_, adding the age-1 survey does not decrease the calculated variability of recruitment deviations."? 

I'd have thought we'd at least 'hope' that the variability decreased (you mean the credible intervals for each year, yes?). I'm missing something....

**Comment by kellijohnson-NOAA** [comment]
No, the calculated variability of the estimates compared to the input/fixed value of sigma_r.

**Comment by andrew-edwards** [comment]
Right, the sigma_r is what is setting the variability (and that hasn't changed). Thanks.
