### ISSUE TITLE
Friday Friday

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#913]
Copying over leftover ones from Wed/Thurs. Add as appropriate.

Chris:
- [x] Make RDS smaller to avoid memory overflow
- [x] Tackle any issues
- [x] #912 

Andy:
- [x] Ideas from our meeting on recruitment appendix.
- [x] Finish checking remaining figs and captions.
- [x] Read over Model Results, to then do 3.7:
- [x] 3.7 - Model projections text - just needs #920.
- [x] Finalize text for age-1 index Appendix (squid issue wrt last year's results).
- [x] Next do #890, need to check some things.
- [x] Check Kelli's latest commit regarding #800.  
- [x] #900 depletion plot - get to rebuild and two checkboxes

Aaron: done for the WEEK.

Kelli:
- [x] Continue on sample size stuff (SRG response)
- [x] WHAM!
